name: Alva frontend stg Build and Deploy

on:
  workflow_run:
    workflows: ["Merge branches on issue update"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    strategy:
      matrix:
        node-version: [18]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: staging

      - uses: pnpm/action-setup@v3
        with:
          version: 9.4.0

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: 'pnpm install'


